name: Check for new CHIRP version

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  push:
    branches:
      - workflows

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scraper
        uses: actions/checkout@v4
        with:
          ref: scraper
          path: scraper

      - name: Compile Scraper
        run: |
          cd scraper
          go build -o ../scraper.bin main.go
          cd ..
          chmod +x scraper.bin

      - name: Checkout wheel-tracking
        uses: actions/checkout@v4
        with:
          ref: wheel-tracking
          path: wheel-tracking

      - name: Check For New CHIRP Release
        id: check
        run: |
          WHEEL_NAME=$(./scraper.bin --wheelName)
          URL_NO_WHEEL=$(./scraper.bin --urlNoWheel)
          echo "wheel_name=$WHEEL_NAME" >> $GITHUB_OUTPUT
          echo "url_no_wheel=$URL_NO_WHEEL" >> $GITHUB_OUTPUT

          FILE_NAME=$(cat wheel-tracking/WHEEL_NAME.txt)
          if [ "$WHEEL_NAME" != "$FILE_NAME" ]; then
            echo "new_version=true" >> $GITHUB_OUTPUT
          else
            echo "new_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Push new version name to wheel-tracking
        if: steps.check.outputs.new_version == 'true'
        run: |
          WHEEL_NAME=${{ steps.check.outputs.wheel_name }}
          echo $WHEEL_NAME > wheel-tracking/WHEEL_NAME.txt

          cd wheel-tracking
          git config user.name "github-action"
          git config user.email "github-actions@github.com"
          git add WHEEL_NAME.txt
          git commit -m "GH Action: update chirp version number"
          git push origin wheel-tracking

      
      - name: Trigger downstream workflow
        if: steps.check.outputs.new_version == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: chirp-new-version
          client-payload: |
            {
              "wheel_name": "${{ steps.check.outputs.wheel_name }}",
              "url_no_wheel": "${{ steps.check.outputs.url_no_wheel }}"
            }
