name: Fetch and Build Latest CHIRP Release

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  push:
    branches:
      - main

jobs:
  build-if-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Scraper
        run: |
          cd scraper
          go build -o ../scraper.bin main.go
          cd ..
          chmod +x scraper.bin

      - name: Check For New CHIRP Release
        id: check
        run: |
          WHEEL_NAME=$(./scraper.bin --wheelName)
          echo $WHEEL_NAME
          FILE_NAME=$(cat WHEEL_NAME.txt)
          if [ "$WHEEL_NAME" != "$FILE_NAME" ]; then
            echo "new_version=true" >> $GITHUB_OUTPUT
            echo $WHEEL_NAME > WHEEL_NAME.txt
          else
            echo "new_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Inject CHIRP Version in Manifest
        if: steps.check.outputs.new_version == 'true'
        run: |
          FULL_URL=$(./scraper.bin --fullURL)
          WHEEL_NAME=$(./scraper.bin --wheelName)

          echo $FULL_URL

          curl -o $WHEEL_NAME "$FULL_URL/$WHEEL_NAME"

          SHA1=$(sha256sum ./$WHEEL_NAME | awk '{print $1}')

          echo $SHA1

          sed -i "s|<SHA1_HERE>|$SHA1|g" io.github.satisflux.chirp.yaml
          sed -i "s|<FULL_URL_HERE>|$FULL_URL|g" io.github.satisflux.chirp.yaml

          cat io.github.satisflux.chirp.yaml


      - name: Push new version name to repo
        if: steps.check.outputs.new_version == 'true'
        run: |
          git config user.name "github-action"
          git config user.email "github-actions@github.com"
          git add WHEEL_NAME.txt
          git commit -m "GH Action: update chirp version number"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Satisflux-Laboratories/chirp-flatpak.git main
